### ISSUE TITLE
Add ircmaxell/password-compat as a dependency

### ISSUE THREAD

**Issue by dosten** [symfony/symfony-demo#10]
I'm running the demo in 5.4 and when i go to the login page i get an error because the password_hash function doesn't exists in 5.4, we can add ircmaxell/password-compat as a dependency to solve this. if you are ok with this i can send a PR :)

PD: Sorry for my english, i'm noob

**Comment by javiereguiluz** [comment]
Thanks for reporting this problem. I consider it a bug because we intend to support even PHP 5.3, so this problem shouldn't happen. And given that the `ircmaxell/password-compat` library doesn't affect the application if you use PHP 5.5 or higher, I think it's safe to always include it.

We'll be very happy if you submit a PR with this change. Thanks!

PS: I know that it may look weird, but in [our composer.json file](https://github.com/symfony/symfony-demo/blob/master/composer.json) we sort dependencies alphabetically and align them with white spaces. Please keep in mind this weirdness when adding the new dependency. Thanks!

**Comment by stof** [comment]
looks like a good idea to me. Our demo should run on as many versions of PHP as possible to make it simpler to use.

**Comment by stof** [comment]
@javiereguiluz I would be in favor of removing the alignment for the same reason we don't align ``=>`` in arrays (even though ``incenteev/composer-parameter-handler`` already puts the min length high enough for most packages...)

**Comment by dosten** [comment]
@stof :+1:
