### ISSUE TITLE
Code style conventions

### ISSUE THREAD

**Issue by voronkovich** [symfony/symfony-demo#174]
What code style conventions should we use?

**Comment by theofidry** [comment]
* [ ] chaining calls

```php
// Choice 1
$object->firstCall()->secondCall()->thirdCall();

// Choice 2
$object
    ->firstCall()
    ->secondCall()
    ->thirdCall();

// Choice 3
$object
    ->firstCall()
    ->secondCall()
    ->thirdCall()
;
```

* [ ] ternary operator

```php
// Choice 1
$result = statement? firstMember: secondMember;

// Choice 2
$result = statement ?firstMember :secondMember;

// Choice 4
$result = statement
    ? firstMember
    : secondMember
;

// ...
```

* [ ] arrays
  * [ ] array notation: `[]` or `array()`
  * [ ] align properties or not
  * [ ] add space between brackets: `[ $something ]` instead of `[$something]

* [ ] naming conventions
  * [ ] follow PHPMD and don't use variable names of 3 characters or less

**Comment by voronkovich** [comment]
Whe should use array() to support php 5.3

**Comment by theofidry** [comment]
Does it make sense? Soon PHP5.4 won't be updated at all. It makes sense for legacy projects but Symfony is, unlike a framework like CodeIgniter, a framework that pushes its users to the latests versions. Symfony3 will require PHP5.5 too.

**Comment by voronkovich** [comment]
For now Symfony supports php 5.3.9 and above: https://github.com/symfony/symfony/blob/2.8/composer.json#L19, I think we should too

**Comment by theofidry** [comment]
Doctrine does not though: [doctrine/doctrine2#composer.json](https://github.com/doctrine/doctrine2/blob/master/composer.json#L16)

**Comment by voronkovich** [comment]
It's because Symfony requires doctrine ~2.3 that supports php 5.3.2 https://github.com/doctrine/doctrine2/blob/2.3/composer.json

**Comment by bocharsky-bw** [comment]
@theofidry We'll switch to 5.5 when Symfony 3 will be released. For now we still support 5.3 until this release.

**Comment by javiereguiluz** [comment]
I'd say that we should follow the same [coding standards used in Symfony](http://symfony.com/doc/current/contributing/code/standards.html).

For the things not defined in that document, let's apply first "the common practice" and then "the common sense". For example: there is no rule about variable name length, so let's apply:

  * First, the common practice: `$em` is the right variable name for the entity manager, because that's the common practice in the Symfony Docs.
  * Second, the common sense: `$q` is probably not a good name for a variable, even if the HTTP query variable is called like that. Let's use `$query`.

**Comment by xabbuh** [comment]
Using `$em` in the docs in my opinion wasn't the best decision we made. But it became a de facto standard and now is widely used (though I would call this a good practice). So, imho it would be totally fine to use `$entityManager` in the demo instead.

**Comment by TomasVotruba** [comment]
@xabbuh I agree with using `$eventManager` instead `$em`. It's easy to confuse `$ed`, `$evm` etc. Also this was in the past due to "better performance". Now better readability is the trend.

**Comment by javiereguiluz** [comment]
Closing it because it seems we've reached an agreement: Symfony conding standards + full-length variables (`$entityManager` instead of `$em`).

**Comment by TomasVotruba** [comment]
@javiereguiluz Great! Thank you
