### ISSUE TITLE
Create ShowSourceBundle

### ISSUE THREAD

**Issue by voronkovich** [symfony/symfony-demo#196]
We should create a simple separate bundle (ShowSourceBundle) and move there the ControllerListener, SourceCodeExtension and related views.
Let's discuss!

**Comment by javiereguiluz** [comment]
At first sight I like this idea because:

  * It allows to separate all the "weird stuff" which is needed for the applciation but that we don't want to show to newcomers directly.
  * It allows to explain how easy is to create additional bundles when needed (AppBundle is just a nice start, not a mandatory limitation)

Let's wait and see if others can point to any drawback for doing this.

**Comment by rasanga** [comment]
I like the idea because I have few confusing points about Symfony3 bundle structure:
* How we are going to name the ShowSourceBundle opposed to best practice doc http://symfony.com/doc/current/cookbook/bundles/best_practices.html
* Where we going to put reusable components inside our application

**Comment by bocharsky-bw** [comment]
I like this idea and agree with Javier :+1:
