### ISSUE TITLE
Error with russian translation after installation

### ISSUE THREAD

**Issue by ar7n** [symfony/symfony-demo#222]
I have just installed symfony-demo, and i see this message:

An exception has been thrown during the rendering of a template ("Unable to load "/Users/arseny/www/symfony_demo/app/Resources/translations/messages.ru.xliff": [ERROR 94] Validation failed: no DTD found ! (in n/a - line 2, column 21)
[ERROR 76] Opening and ending tag mismatch: trans-unit line 198 and body (in n/a - line 254, column 16)
[ERROR 76] Opening and ending tag mismatch: body line 4 and file (in n/a - line 255, column 12)
[ERROR 76] Opening and ending tag mismatch: file line 3 and xliff (in n/a - line 256, column 9)
[ERROR 77] Premature end of data in tag xliff line 2 (in n/a - line 257, column 1)") in default/homepage.html.twig at line 14.

when i go to http://localhost:8000/en, everything is ok.

**Comment by javiereguiluz** [comment]
@ar7n thanks for reporting this error. In fact, this issue was fixed a few days ago in [this pull request](https://github.com/symfony/symfony-demo/pull/212). I'm going to release a new version of the Symfony Demo application to publish the bugfix. Sadly, it takes 24 hours to make the new version available in our CDN cache, so we'll need to wait until tomorrow for the real fix.

**Comment by javiereguiluz** [comment]
The new 0.6.0 version has been released (https://github.com/symfony/symfony-demo/releases/tag/v0.6.0). It will be available in 24 hours. Thanks!
