### ISSUE TITLE
Paginator for backend

### ISSUE THREAD

**Issue by ccab** [symfony/symfony-demo#223]
I'd like to add the paginator also in the backend and btw sorting the columns to improve the user experience

**Comment by bocharsky-bw** [comment]
:+1: for paginator since we already have it in the frontend

**Comment by voronkovich** [comment]
:+1:

**Comment by stof** [comment]
I'm :+1: on it. Showing unpaginated lists is a bad idea IMO.

@javiereguiluz does it need to be implemented here or in your admin bundle though ?

**Comment by javiereguiluz** [comment]
I'm :-1: because the demo application is not something you use in the real world ... but something you use to learn how real-world-looking apps work. If we already have a pagination example in the frontend, that's enough to show the newcomer how it's done.

@stof I don't fully understand your comment because this demo app doesn't use any bundle for the admin backend.

**Comment by stof** [comment]
oh, I thought we were using your EasyAdminBundle. I should have checked

**Comment by voronkovich** [comment]
@javiereguiluz, but @ccab wants to add a sorting and etc., no only the pagination

**Comment by javiereguiluz** [comment]
@voronkovich in that case I also think it's a bad idea. The "good practice" here should be: if you need sorting, pagintion and all those common features ... use Sonata or any other backend bundle.

**Comment by ccab** [comment]
Ok so let's keep it in the frontend

**Comment by javiereguiluz** [comment]
Closing it as "won't fix" for the mentioned reasons.
