### ISSUE TITLE
HTTP 405 in production when deleting a post

### ISSUE THREAD

**Issue by dzuelke** [symfony/symfony-demo#299]
In production deleting a post in the admin interface gives a 405 error.

The reason is that the AppCache interferes with `http_method_override` being enabled, see notes at http://symfony.com/doc/current/reference/configuration/framework.html#http-method-override

What should the solution be? I'd say adding `Request::enableHttpMethodParameterOverride();` to `web/app.php`, but the alternative of course is disabling `http_method_override` (not supported by most browsers though AFAIK), so I just wanted to double check before sending a pull request :)

**Comment by voronkovich** [comment]
@dzuelke, using `Request::enableHttpMethodOverride` is recommended solution for this issue.

**Comment by voronkovich** [comment]
I think it's better to disable HTTP caching for the admin panel.

**Comment by stof** [comment]
if you use the method override and the AppCache, you indeed need to call the method explicitly before using the cache instead of using the config setting (which would overwrite it only when booting the AppKernel, which is too late for AppCache).
And the documentation you linked explictly mentions this

**Comment by dzuelke** [comment]
Yeah I realize that @stof; the question was whether `http_method_override` should stay on or not. I'll send a PR.

**Comment by dzuelke** [comment]
#300 is the PR
