### ISSUE TITLE
Add an example .php_cs

### ISSUE THREAD

**Issue by ABM-Dan** [symfony/symfony-demo#395]
Many projects nowadays use php-cs-fixer, and the new version is losing the ability to run `--config=symfony23`, leaving us with the task to manually craft a `.php_cs` file on our own, it would be helpful to have an example here on symfony-demo.

**Comment by javiereguiluz** [comment]
@ABM-Dan thanks for proposing this. I didn't know they were going to remove that option. That's a big reason to include an example of the `.php_cs` file in this demo app.

I'll wait a few days to see if someone from the community wants to contribute this feature. Otherwise, I'll implement it myself. Thanks!
