### ISSUE TITLE
Symfony demo bundle

### ISSUE THREAD

**Issue by jkufner** [symfony/symfony-demo#518]
Just like this symfony-demo app, there should be a **symfony-bundle-demo**, a best practices example how to create nice reusable Symfony bundle — http://symfony.com/doc/current/bundles/best_practices.html.

The bundle could extend this demo with an additional entity, custom styles, and few small features.

**Comment by apetitpa** [comment]
I believe Symfony is going to a bundleless architecture so I wonder if this is necessary.

**Comment by javiereguiluz** [comment]
Yes, the trend is "bundle-less apps" ... but I guess @jkufner was also referring to third-party bundles. We have this article --> http://symfony.com/doc/current/bundles/best_practices.html but not a sample code repository. I still don't have an opinion about this proposal.

**Comment by apetitpa** [comment]
Thank you @javiereguiluz I misunderstood the request I see what he meant now

**Comment by jkufner** [comment]
Yes, I'm referring to the third-party bundles. I found them to be one of the major features over Laravel and other frameworks. The best practices is useful document, but I really miss a good and complete example.

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix" because:

1) The concept of "app bundle" will disappear soon, so there's no need to teach how to create great bundles.
2) Third-party bundles will continue to exist ... but we can't create one in this repository, because it's just a demo application. If we decide to do this, it will be in a different repository.

(By the way, this won't be easy because we have problems even to define what's the best dir structure for bundles, see: https://github.com/symfony/symfony-docs/issues/5691)
