### ISSUE TITLE
is CodeExplorerBundle mean to be reusable bundle?

### ISSUE THREAD

**Issue by sruj** [symfony/symfony-demo#545]
is CodeExplorerBundle mean to be reusable bundle?

(where is the place to ask this question, and not opening new issue?)

**Comment by javiereguiluz** [comment]
It's OK to open issues to ask this kind of questions!

CodeExplorerBundle was created because of the old way of developing Smyfony apps. However, with Symfony Flex it will be no longer necessary. I have a prototype of Symfony Demo with Symfony Flex on my local computer. It's almost working. All bundles are gone and the whole app is much simper now. I'll create the PR once Flex is open sourced. Thanks!

**Comment by sruj** [comment]
ok, thanks.
