### ISSUE TITLE
Unit tests not running with PHPUnit 6

### ISSUE THREAD

**Issue by wcomnisky** [symfony/symfony-demo#553]
I'm getting the following:
<pre>
$ phpunit -v
Class "\DAMA\DoctrineTestBundle\PHPUnit\PHPUnitStaticDbConnectionListener" does not implement the PHPUnit\Framework\TestListener interface
</pre>

Changeset (latest master): 46824f1
PHP 7.1.4-1
PHPUnit 6.0.7

**Comment by javiereguiluz** [comment]
@dmaicher could you please take a look at this error? Thanks!

**Comment by dmaicher** [comment]
Well my bundle `dama/doctrine-test-bundle` currently has two maintained versions. `1.x` is for phpunit < 6 and `2.x` is for phpunit >= 6.

You seem to be using your own global phpunit version for running the tests? As you can see in the `composer.json` of master currently we are using the following:

```json
"dama/doctrine-test-bundle"            : "^1.0",
"phpunit/phpunit"                      : "^4.8 || ^5.0",
```

So if you stick to the required phpunit version then all is good. Otherwise for phpunit 6 you have to require `dama/doctrine-test-bundle: ^2.0` :wink: 

Anyway the whole testsuite is currently not compatible with phpunit 6:

```
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /var/www/symfony-demo/tests/AppBundle/Utils/SluggerTest.php on line 26
```

@javiereguiluz we could update everything to use phpunit 6 though?

**Comment by javiereguiluz** [comment]
@dmaicher yes, cannot upgrade to PHP 7 yet. Symfony Demo follows the most recent stable version of Smyfony, so we'll upgrade to PHP 7 in November 2017, when Symfony 4 is released.

**Comment by dmaicher** [comment]
@javiereguiluz ok then nothing to fix here for now imho

**Comment by javiereguiluz** [comment]
Closing this as "won't fix" ... until we update to Symfony 4.0 on November 2017. Thanks!

**Comment by CruzyCruz** [comment]
@javiereguiluz 

Sorry to bother you with a closed issue but I do not understand this comment:

> yes, cannot upgrade to PHP 7 yet. Symfony Demo follows the most recent stable version of Symfony, so we'll upgrade to PHP 7 in November 2017, when Symfony 4 is released.

In this [article](http://symfony.com/blog/symfony-achieves-100-php7-compatibility) (Symfony blog), you say that all maintained branch of Symfony are compatible with PHP 7. Actually Symfony demo uses SF 3.2 wich is not a LTS but is maintained till 07/2017. 

Do you mean that the custom application code is not PHP 7 compatible ?

Another point is that in [.travis.yml](https://github.com/symfony/symfony-demo/blob/master/.travis.yml), testing under PHP >=7 is required. So I am a bit lost.

Thank you a lot for your explanations.

**Comment by javiereguiluz** [comment]
@CruzyCruz the difference is between supporting PHP 7 or requiring PHP 7. The current Symfony Demo app runs on PHP 5 and 7. But requiring PHP 7 will mean that people still using PHP 5 (still half of developers!!!) won't be able to run the app.

That's why we always follow what Symfony does: before it requires PHP 5.3 and we did that. Today it requires PHP 5.5, and we do that. In November it will require PHP 7.1 ... and we'll do that change too.

**Comment by CruzyCruz** [comment]
OK I understand now, it is a big difference !

Thank you Javier.
