### ISSUE TITLE
locale in URL

### ISSUE THREAD

**Issue by XPanel** [symfony/symfony-demo#622]
hello,
is there a way to have in url : ....app_dev.php/pt-br/admin/post/

instead of : app_dev.php/pt_BR/admin/post/

there are some recommendations in SEO to not use underscore symbol and avoid uppercase 

thank you,

**Comment by javiereguiluz** [comment]
The first thing to take into account is that `pt_BR` is the valid locale for the Brazilian Portuguese language and `pt-br` is not. 

If the locale is correct, Symfony handles everything automatically, saving you a ton of work. If you want to use a value that is not a valid locale, you must treat it like any other routing parameter and do all that work yourself. We can't change the Symfony Demo app because of that and I'd say is a good trade-off to not do that in any of your applications either.

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix" because of the above reasons: the effort required to change this is not worth it for the Demo app. Thanks!
