### ISSUE TITLE
Update policy

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-demo#76]
Do we need to discuss when the committed `composer.lock` file will be updated? For example, currently you will download an archive containing Symfony 2.7.0 (the latest Symfony version is 2.7.1).

**Comment by stof** [comment]
Well, this is a demo application. Application must commit their lock files. It is one of the important composer best practices.
IMO, it is not a big issue if it does not always lock the latest release of Symfony. However, we should ensure that it use the latest one at the time of a symfony-demo release (i.e. we should update deps before doing a new release rather than using old deps).

what do you think @javiereguiluz ?

**Comment by javiereguiluz** [comment]
If you ask my personal opinion on updates: when I was young I always wanted to update everything to the latest version. Now that I'm ~~old~~ experienced, I prefer that other ~~fools~~ developers test those cutting-edge versions first. So I prefer to always use the `N-1` version, where `N` is the latest one.

Anyway, I'll agree on any decision you make about this, so I'm ready to update the dependencies.

**Comment by stof** [comment]
@javiereguiluz I think that for the demo app, it is OK to be on the latest version (note that I'm talking about using stable versions, not dev branches).

**Comment by javiereguiluz** [comment]
PK then, Let's always use the latst stable version. I've made the needed changes in #77. Thanks.

**Comment by javiereguiluz** [comment]
Closing this issue as "solved".
